replicaCount: 1

application:
  track: stable
  migrate:
    image: governmentpaas/psql
    # run: false # set by GitLab CD
    command: cat /migrations/*.sql | psql "postgres://$(DATABASE_USER):$(DATABASE_PASSWORD)@$(DATABASE_SERVER)/$(DATABASE_NAME)"

environment:
  mainnetHorizonUrl: https://stellar-horizon.satoshipay.io
  testnetHorizonUrl: https://stellar-horizon-testnet.satoshipay.io
  # databaseUrl

postgresql:
  enabled: true
  postgresqlUsername: postgres
  postgresqlDatabase: coordinator
  # postgresqlPassword:
  persistence:
    storageClass: standard
  resources:
    requests:
      cpu: 50m
      memory: 100Mi

image:
  repository: satoshipay/multisig-coordinator
  tag: v0.1.0
  pullPolicy: IfNotPresent
  secrets: []

service:
  type: ClusterIP
  internalPort: 3000
  externalPort: 80
  name: http
  annotations: {}

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  baseURL: https://api-dev.satoshipay.io/
  path: /

resources:
  requests:
    cpu: 10m
    memory: 40Mi

nodeSelector: {}

tolerations: []

affinity: {}
